version: "3"
services:
  boyo-bot:
    build: .
    container_name: boyo-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/memory.txt:/memory.txt
      - ./config.json:$HOME/.config/revChatGPT/config.json
